version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
